### PR TITLE
boolean checkboxen

### PR DESCRIPTION
**Pull request by georules**
A potential solution for https://github.com/enjalot/Inlet/issues/23

### CODE REVIEW

**Comment by georules** [comment]
sorry there's a bug with this.  unsetting the checked attribute sometimes does not cause chrome to rerender the checkbox as unchecked.  I'm working on a solution.

**Comment by georules** [comment]
Check out what this is :laughing: 
var b = Boolean("false")

Also setting/removing the checked attribute doesn't always re-render the correct state of the checkbox (Chrome bug?), so I'm removing the checkbox and creating a new one every time we need to display it.

**Comment by curran** [comment]
This is awesome! It works on my machine. Thanks for doing this work.

**Comment by enjalot** [comment]
Awesome!

**Comment by enjalot** [comment]
thanks so much. I've published to npm as 0.1.7

**Pull request merged**
